import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from './Providers';
import SessionGuard from '@/app/components/SessionGuard';
import NavBar from '@/app/navbar';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/config/authOptions';

import Login from "./components/Login";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  if(session) {
    return (
    <html lang="en" className="h-full bg-gray-100">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <Providers>
          <SessionGuard>

            <NavBar />
            {children}
          </SessionGuard>
        </Providers>
        
      </body>
    </html>
    );
  } else {
    return (
    <html lang="en" className="h-full bg-gray-100">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <Providers>
          <SessionGuard>
            <NavBar />
            <Login/>
          </SessionGuard>
        </Providers>
      </body>
    </html>
    );
  };
}
